version = 0.1

[default]

[default.deploy.parameters]
stack_name = "animores-server"
resolve_s3 = true
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
disable_rollback = true
s3_prefix = "animores-server"
