AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Animore appliaction server api

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  SpringOnLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: animores.animoresserverapi.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 2048
      SnapStart:
        ApplyOn: "PublishedVersions"
      AutoPublishAlias: "stage"
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

#Outputs:
#  AnimoresServerApi:
#    Description: URL for application
#    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/animores'
#    Export:
#      Name: AnimoresServerApi
