spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://${db_host}:3306/animores
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${redis_endpoint}
    port: 6379

  cloud:
    aws:
      credentials:
        accessKey: ${s3_access_key}
        secretKey: ${s3_secret_key}
      s3:
        bucket: ${bucket_name}
      region:
        static: ${s3_region}
      stack:
        auto: false

  jwt:
    secret-key: ${jwt_secret_key}
    expiration-hours: 24
    issuer: kangmo
    redis:
      host: ${redis_endpoint}
      port: 6379

mail:
  smtp:
    host: ${mail_host}
    port: ${mail_port}
    username: ${mail_username}
    password: ${mail_password}
    auth: true
    starttls:
      enable: true
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
